### ISSUE TITLE
deadlock server

### ISSUE THREAD

**Issue by Hedgehogues** [pypiserver/pypiserver#304] opened 2020-04-17 19:00 UTC
Hello. I run docker-compose with auth. Sometimes, I open browser with server and after that, my pypi-server goes to deadlock and it doesn't response anymore. I need to wait a lot and close the page with pypiserver or reboot docker container. What reasons this case?

**Comment by davidt99** [comment] 2020-06-19 14:47
Use gunicorn as a server instead of the default one

**Comment by mplanchard** [comment] 2021-02-06 17:45
I think this is probably a duplicate of #286, so I'll close this issue in favor of that one. Using gunicorn as the WSGI server or running behind a reverse proxy should help

**Closed by mplanchard** 2021-02-06 17:45 UTC
