### ISSUE TITLE
Default --fallback-url causing 403 error after change to restrict non HTTPS access to PyPI 

### ISSUE THREAD

**Issue by lgenasi** [pypiserver/pypiserver#183] opened 2017-10-30 12:29 UTC
After the changes made to PyPI which restrict access to only HTTPS (https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html), the default fallback url used by pypiserver does not work anymore as it uses HTTP.

`  --fallback-url FALLBACK_URL
    for packages not found in the local index, this URL will be used to
    redirect to (default: http://pypi.python.org/simple)`

The default for this needs to be changed to https in order to work with the new changes.

**Workaround** is to add `--fallback-url https://pypi.python.org/simple` as an option when starting pypiserver.

**Comment by dpgeekzero** [comment] 2017-10-30 13:52
Thanks for the heads up, I've been wondering why my local pypi server stopped working.

**Comment by jkpubsrc** [comment] 2017-10-30 14:38
Sorry, I don't understand. What has this to do with PyPiServer? If PyPi now uses https and pip connects to pypi.python.org using https, and if a local server is running on http, what exactly do I need the fallback URL for? Please explain as I ran into some trouble regarding http/https with pip yesterday and found this quite strange. Maybe this hat to do with this issue, though it was a different matter.

**Comment by mplanchard** [comment] 2017-10-30 14:51
This is a duplicate of #179. Please see the discussion there. We will be updating the default ASAP, but as @lgenasi says, the workaround in the meantime is to manually specify the fallback URL.

**Closed by mplanchard** 2017-10-30 14:51 UTC
Labels: resolved.Duplicate
