### ISSUE TITLE
HTTPError: 405 Method Not Allowed

### ISSUE THREAD

**Issue by pedro-cf** [pypiserver/pypiserver#540] opened 2023-11-20 20:00 UTC
Hello I can't seem to get my pypiserver to work properly...

I set it up with:

htpasswd -sc .htpasswd myuser
docker run -d -p 8081:8080 -v $PWD/.htpasswd:/data/.htpasswd pypiserver/pypiserver:latest run -P .htpasswd packages

and when I use:
twine upload --repository-url http://localhost:8081/simple/ --username myuser --password mypassword dist/*

I get:

Uploading distributions to http://localhost:8081/simple/
Uploading cdse_interface-1.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 kB • 00:00 • ?
WARNING Error during upload. Retry with the --verbose option for more details.
ERROR HTTPError: 405 Method Not Allowed from http://localhost:8081/simple/
Method Not Allowed

whats wrong ?

**Comment by GooseYArd** [comment] 2023-12-12 19:54
I ran into this issue a moment ago and after stepping through the code with the debugger, found that I needed to remove "/simple" from the repository URL I was using. Hope that helps!

**Comment by dee-me-tree-or-love** [comment] 2024-08-20 09:01
Hello @pedro-cf and @GooseYArd! Sorry for joining this discussion late. @GooseYArd thanks a lot for your response, I think this is indeed the correct solution. @pedro-cf could you confirm that this has worked out? 

I'll close this issue since it's been silent for a while, hope the problem is resolved 😊 Feel free to re-open this is needed.

**Closed by dee-me-tree-or-love** 2024-08-20 09:01 UTC
