### ISSUE TITLE
Support and test against Python 3.5

### ISSUE THREAD

**Issue by mplanchard** [pypiserver/pypiserver#108] opened 2016-01-20 20:08 UTC
This should just be a matter of adding a 3.5 environment to the test suites. I've got a pypiserver running on 3.5 locally, and it works well.

**Comment by mplanchard** [comment] 2016-01-20 22:19
Not a big enough deal to require an issue. Deleting.

**Comment by ankostis** [comment] 2016-01-20 22:22
No prob, it is perfectly fine this issue.
I had not looked at it when I wrote about skipping issues.
Lets close it when we have merged into master.

**Comment by ankostis** [comment] 2016-01-20 23:08
Duplicate of #110.

**Closed by ankostis** 2016-01-20 23:08 UTC
Labels: Maintainance
