### ISSUE TITLE
PyPI backend and redirections

### ISSUE THREAD

**Issue by gracinet** [pypiserver/pypiserver#38] opened 2013-04-27 15:03 UTC
Hi, thanks for pypiserver, simple and useful !

Here's a tricky problem when running pypiserver with fallback to a mirror index, not sure if it should be fixed within pypiserver or not.
See also https://bitbucket.org/loewis/pep381client/issue/22

The main PyPI server does some 301 redirections (to fix some mispellings). That's not something a mirror can easily reproduce (see above cited issue on pep381client).
The combination of pypiserver and a mirror leads to installation errors. 
Fixing one's spellings is not practically possible, because they occur a lot through dependencies.

### Reproduction

Assume for instance that pypiserver does not hold packages for 'babel'.

Client applications (such as pip) try e.g., '/simple/babel' (proper spelling is 'Babel')

- On the main PyPI, they get a 301 response to '/simple/Babel' -> ok

- On a PyPI mirror, they get a 404, then they fetch the whole '/simple/' page, analyse it,   find 'Babel' in it, correct the spelling and retry -> inefficient, but ok

- On pypiserver with fallback on a mirror, they get:
  - a 303 to the mirror ('/simple/babel')
  - then, a 404 from the mirror
  - then they fetch the '/simple' page *from pypiserver*, which does not list the wished distribution ('Babel') -> ERROR

### Workarounds 

My workaround for now is to setup 301 redirections for commonly mispelled distributions in the mirror as well (in our case, the mirror is ours), but that's a maintenance burden and does not scale.
 
Another possibility is to manually add commonly mispelled distributions in pypiserver and use '-U'. That's insatisfactoy for the same reasons.

### Conclusion

Mispellings in dependencies are really common, since many distribution authors don't even realize their spelling is wrong. Any idea ?

**Comment by ankostis** [comment] 2015-02-23 15:01
@gracinet Do you think that a workaround would be to invoke `pip` with ``--extra-index-url <pypiserver_url>`` instead of ``--index-url <pypiserver_url>``?

**Comment by gracinet** [comment] 2015-02-23 16:14
@ankostis, nice to see some new activity around pypiserver !
About your suggestion, I'm not sure and I don't have an easy way to test it anymore : we dropped the pep381 mirror instance completely since then, the main PyPI became much more robust shortly afterwards (that's not the only problem we had with pep381)

If that helps you, I can try and reproduce again, then tell about the suggestion. 

As a side note, we were affected by this problem with pip, but with zc.buildout. I don't remember so well, but maybe the reading of the whole `simple/` path was actually implemented in setuptools. I don't know if that would still be true, with the many changes and sanitization that the pypa's been doing since then.

**Comment by ankostis** [comment] 2015-02-23 20:01
@gracinet I wouldn't want to burden you, but i would appreciate it if you remember some details to reproduce the error (even without the the pep381 mirror downstream).

In any case i plan to release the new version v1.1.7 with the new usage-recommendation and then assume this bug to be fixed.  In case it is not, please comment on it.

**Comment by gracinet** [comment] 2015-02-26 23:09
@ankostis yes, it works with pip --extra-index-url on current pip 6 and setuptools 12 ! 

The behaviour is otherwise mostly the same than it was with older version with just --index-url, except that pip now issues one deprecation warning. 

That being said, we're calling this whole stack mostly through zc.buildout, which does not support multiple indexes (nor does easy_install, as far as I can see). Maybe an extension such as gp.vcsdevelop can provide a workaround, as it relies internally on pip, but I wouldn't bet on that too much, since it's meant to pull from remote VCSes anyway.

Tests done on the same version of pep381 mirror as in 2013 (revived a backup).

**Comment by ankostis** [comment] 2015-02-26 23:36
@gracinet When you say "behaviour is otherwise mostly the same", do you mean that you still cannot resolve misspelled dependencies?
Or doy you mean that the pypiserver fails on them, like it used to, but since it is not pip's "main" index, the pip-action completes ok?

**Comment by gracinet** [comment] 2015-02-26 23:58
@ankostis yes I mean misspelled dependencies can't be resolved with pip install --index-url PYPISERVER_URL, but they can with --other-index-url (as you suggested).

With --index-url only, the sequence is exactly the same as first described.
With --other-index-url, one can see pip calling both servers from the beginning and finding the misspelled dependency in the main PyPI.

**Comment by ankostis** [comment] 2015-02-28 00:35
Thanks a lot, considered resolved with the new `--extra-index-url` advice.

**Closed by ankostis** 2015-02-28 00:35 UTC
Labels: Bug, Feature

**Comment by ankostis** [comment] 2016-06-17 20:31
#140 implemented redirection when *un-normalized* packages requested - not *misspelled* ones, but should probably cover 99% of cases.
