### ISSUE TITLE
Logs not showing when running from docker

### ISSUE THREAD

**Issue by zeroohub** [pypiserver/pypiserver#358] opened 2020-11-11 08:41 UTC
I am in ubuntu 20.04.
When i start pypiserver with command
```
docker run --rm -p 8080:8080 -v /tmp/packages:/data/packages pypiserver/pypiserver -P . -a .
```
and then, try to install some packages
```
pip install --no-cache-dir --force-reinstall --exists-action=w example-pkg --trusted-host 127.0.0.1 --index-url http://127.0.0.1:8080/simple/
```
It doesn't show any logs from console. But if i stopped the container, it will show all accumulated logs at once.
![image](https://user-images.githubusercontent.com/3849613/98788916-7edd4480-243c-11eb-973d-9515cc1cb900.png)

Notice in the images above, before blank lines, I download one package, But it doesn't show any logs. After i stop container, it show 3 logs at once.

**Comment by elfjes** [comment] 2020-11-15 20:15
Does the problem persists when you bind the container to the terminal? ie `docker run -t ...`

**Comment by mplanchard** [comment] 2020-11-15 21:48
Interestingly, I am not seeing this behavior on Ubuntu 20.04 when I ran pretty much the same command with `pypiserver/pypiserver:latest` or `pypiserver/pypiserver:unstable`. Do you know which docker image tag you're running?

**Comment by elfjes** [comment] 2020-11-15 22:01
@mplanchard I can confirm this issue on Ubuntu 20.04 with `pypiserver/pypiserver:v1.4.2`. Running with `-t` solves it though, or at least circumvents the problem. Interesting that it's not an issue for you

**Comment by mplanchard** [comment] 2020-11-15 22:07
Yeah that is really odd. Just to confirm:

Running the command:
![image](https://user-images.githubusercontent.com/6752481/99198148-54e99200-275c-11eb-8d5d-c8ad8a6a2fbe.png)

Output for an attempt to install a package:
![image](https://user-images.githubusercontent.com/6752481/99198175-6fbc0680-275c-11eb-9e6d-278010bc54c6.png)

It's also weird that @zeroohub isn't getting the config output even though they're running with `-v`

**Comment by elfjes** [comment] 2020-11-15 22:19
The issue here I believe is that the logs are not properly piped/redirected to stdout. They are being produced by pypiserver but get stuck somewhere in a buffer. This may be a host issue though. I thought it might also be shell dependent, as I run bash, but I'm experiencing the same on `sh` and `zsh`.

**Comment by mplanchard** [comment] 2020-11-15 22:22
I'm also running bash. I wonder if there's some kind of system-dependent configuration for how much data needs to be written to the log buffer before it gets flushed?

**Comment by zeroohub** [comment] 2020-11-27 08:36
I am running this in k8s, it also doesn't produce logs correctly. After some test, i find that if i switch server to `paste`, it works properly.

**Comment by mplanchard** [comment] 2021-02-06 17:35
I believe this should be resolved in the current master. If you've got the time, could you check and see if this is still happening for you with the `unstable` docker tag?

**Comment by mplanchard** [comment] 2021-02-06 22:54
ah, I did some more experimenting with this while working with gunicorn, and it's not currently solved in master. However, I did figure out the root cause, which is python's default buffering of the stdout and stderr streams. Setting `PYTHONUNBUFFERED=t` in the docker file solves it. Expect that in an upcoming commit!

**Comment by mplanchard** [comment] 2021-02-06 22:55
In the meantime, if you set this in your `docker run` command, it should resolve the issue I think

**Closed** 2021-02-07 23:04 UTC
Labels: backport
