### ISSUE TITLE
paste.ini

### ISSUE THREAD

**Issue by michaelkuty** [pypiserver/pypiserver#125] opened 2016-03-19 08:39 UTC
Hello i would like to ask about paste.ini config

```
[composite:main]
use = egg:Paste#urlmap
/unstable/ = unstable
/ = stable

[app:stable]
use = egg:pypiserver#main
root = /srv/pypiserver/stable
authenticated = update,download
password_file = /srv/pypiserver/htpasswd.txt

[app:unstable]
use = egg:pypiserver#main
root = /srv/pypiserver/unstable
htpasswd=/srv/pypiserver/htpasswd.txt

[server:main]
use = egg:gunicorn#main
host = 0.0.0.0
port = 9000
workers = 2
accesslog = -

   gunicorn --paste paste.ini
```

but i cannot propagate passwords and authentificated down into pypiserver, please what i make wrong ?

**Comment by mplanchard** [comment] 2016-03-21 14:54
Hello! Could you please paste here the command that you are using to start your `pypiserver` instance? Thanks.

**Comment by michaelkuty** [comment] 2016-03-21 15:17
/srv/pypiserver/bin/gunicorn --paste /srv/pypiserver/paste.ini

**Comment by mplanchard** [comment] 2016-03-22 00:17
@michaelkuty Please try using `passwords` as the key, rather than `htpasswd` or `password_file`, and let me know the results.

**Comment by michaelkuty** [comment] 2016-03-22 21:09
[app:unstable]
	use = egg:pypiserver#main
	root = /srv/pypiserver/unstable
	authenticated = update,download
	passwords=/srv/pypiserver/htpasswd.txt

	127.0.0.1 - - [22/Mar/2016:22:07:49 +0100] "GET /simple/django-leonardo/ HTTP/1.1" 200 457 "-" "pip/8.0.2 {\"cpu\":\"x86_64\",\"distro\":{\"id\":\"trusty\",\"libc\":{\"lib\":\"glibc\",\"version\":\"2.4\"},\"name\":\"Ubuntu\",\"version\":\"14.04\"},\"implementation\":{\"name\":\"CPython\",\"version\":\"2.7.6\"},\"installer\":{\"name\":\"pip\",\"version\":\"8.0.2\"},\"openssl_version\":\"OpenSSL 1.0.1f 6 Jan 2014\",\"python\":\"2.7.6\",\"system\":{\"name\":\"Linux\",\"release\":\"3.13.0-43-generic\"}}"
	127.0.0.1 - - [22/Mar/2016:22:07:50 +0100] "GET /packages/django-leonardo-1.0.5.tar.gz HTTP/1.1" 200 - "-" "pip/8.0.2 {\"cpu\":\"x86_64\",\"distro\":{\"id\":\"trusty\",\"libc\":{\"lib\":\"glibc\",\"version\":\"2.4\"},\"name\":\"Ubuntu\",\"version\":\"14.04\"},\"implementation\":{\"name\":\"CPython\",\"version\":\"2.7.6\"},\"installer\":{\"name\":\"pip\",\"version\":\"8.0.2\"},\"openssl_version\":\"OpenSSL 1.0.1f 6 Jan 2014\",\"python\":\"2.7.6\",\"system\":{\"name\":\"Linux\",\"release\":\"3.13.0-43-generic\"}}

	(leonardo)root@leonardo-multi:/srv/leonardo/sites/leonardo# pip install --index-url http://localhost:9000/simple django-leonardo --trusted-host http://localhost/simple/
	Collecting django-leonardo
	  Downloading http://localhost:9000/packages/django-leonardo-1.0.5.tar.gz (6.5MB)
	    100% |████████████████████████████████| 6.5MB 8.4MB/s 

not works for me

**Comment by mplanchard** [comment] 2016-03-22 21:43
Are you expecting to be unable to download packages without authenticating? If so, `pypiserver` does not provide that functionality, and you will need to configure `gunicorn` appropriately to require authentication prior to access. 

The `htpasswd` file for pypiserver is there to allow authenticated package uploads only. Are you able to upload packages to your repository without authentication?

I have never used `gunicorn`, so I can't help you there, but I know that `nginx` allows you to use an `htpasswd` file for http basic authentication. You can use the same file as the one you specify for package uploads, and the http basic request is used for authentication.

**Comment by michaelkuty** [comment] 2016-03-22 21:47
(pypiserver)root@leonardo-multi:/srv/pypiserver# cat htpasswd.txt 
    majklk:test


	[leonardo-unstable]
	repository: http://10.10.10.122:9000
	username:majklk
	password:test

       python setup.py sdist upload -r leonardo-unstable
       running upload
       Submitting dist/django-leonardo-1.0.6.dev147.tar.gz to http://10.10.10.122:9000 error: <urlopen error [Errno 104] Connection reset by peer>

      10.10.10.122 - majklk [22/Mar/2016:22:45:55 +0100] "POST / HTTP/1.1" 403 705 "-" "Python-urllib/2.7"

**Comment by ankostis** [comment] 2016-03-22 23:33
@mplanchard wrote:
> Are you expecting to be unable to download packages without authenticating? If so, pypiserver does not provide that functionality

But this is supposed to be working, by setting `authenticated = update,download`; if not, then it's a bug.

**Comment by mplanchard** [comment] 2016-03-23 01:52
@ankostis Looking through the code, you're right. We do a pretty poor job of documenting that in the README, though.

**Comment by mplanchard** [comment] 2016-03-23 02:35
@ankostis, you're right. I missed that, sorry. @michaelkuty, I'm not sure where the settings are getting dropped. I'll keep looking into it, and in the meantime, let me know if you find anything.

**Comment by mplanchard** [comment] 2016-03-23 02:56
@michaelkuty, just to verify, you showed the cat output of your htpasswd file to have the password 'test' unencrypted. Is that actually the case, or did you alter it for demonstration purposes?

**Comment by michaelkuty** [comment] 2016-03-23 09:09
I show htpasswd and with correct password i cannot upload package for me I
use wrong config or not works
Dne 23. 3. 2016 3:56 napsal uživatel "Matthew Planchard" <
notifications@github.com>:

**Comment by mplanchard** [comment] 2016-03-23 15:01
I have confirmed that the expected functionality does not work using a paste-deploy process. For future reference, my configuration is below:

````
[composite:main]
use = egg:Paste#urlmap
/ = testing

[app:testing]
use = egg:pypiserver#main
root = /home/pypi/packages
authenticated = update,download
password_file = /home/pypi/.htaccess

[server:main]
use = egg:gunicorn#main
host = 0.0.0.0
port = 80
workers = 5
accesslog = -
````

Using twine to upload with the correct profile, I get a 403 forbidden error:

````
(Python35)[Nautilus@Nautilus-2 dist]$ twine upload -r local *
Uploading distributions to http://localhost:8080
Uploading pyinvision-0.4.3.tar.gz
HTTPError: 403 Client Error: Forbidden for url: http://localhost:8080/
````

And downloads are unimpeded:

````
(Python35)[Nautilus@Nautilus-2 pypi]$ pip install --download . --no-deps --index-url http://localhost:8080/ --trusted-host localhost pyinvision
DEPRECATION: pip install --download has been deprecated and will be removed in the future. Pip now has a download command that should be used instead.
Collecting pyinvision
  Downloading https://pypi.i2.ihiji.net/packages/pyinvision-1.0.0.tar.gz (381kB)
    100% |████████████████████████████████| 389kB 4.0MB/s
  Saved ./pyinvision-1.0.0.tar.gz
Successfully downloaded pyinvision
````

Starting the server using the same options from the command line (not using gunicorn), all functionality works as intended:

Twine upload:

````
(Python35)[Nautilus@Nautilus-2 dist]$ twine upload -r local *
Uploading distributions to http://localhost:8080
Uploading pyinvision-0.4.3.tar.gz
Uploading pyinvision-0.5.0.tar.gz
Uploading pyinvision-0.5.1.tar.gz
Uploading pyinvision-0.5.3.tar.gz
Uploading pyinvision-0.5.4.tar.gz
Uploading pyinvision-0.5.5.tar.gz
Uploading pyinvision-0.7.1.tar.gz
Uploading pyinvision-1.0.0.tar.gz
Uploading pyinvision-1.0.1.tar.gz
````

Downloads are authenticated:

````
(Python35)[Nautilus@Nautilus-2 tmp]$ pip install --download . --no-deps --index-url http://localhost:8080/ --trusted-host localhost pyinvision
DEPRECATION: pip install --download has been deprecated and will be removed in the future. Pip now has a download command that should be used instead.
Collecting pyinvision
User for localhost:8080: pypi
Password:
  Downloading http://localhost:8080/packages/pyinvision-1.0.1.tar.gz (382kB)
    100% |████████████████████████████████| 389kB 62.7MB/s
  Saved ./pyinvision-1.0.1.tar.gz
Successfully downloaded pyinvision
You are using pip version 8.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
````

The working pypiserver instance was started with the following:

````
pypi-server -p 80 -a update,download -P /home/pypi/.htaccess -vv /home/pypi/packages
````

And the non-functional unicorn server was started with the following:

````
gunicorn --paste paste.ini
````

In addition to the lack of expected functionality, our documentation needs to be updated to indicate how to pass options to the gunicorn server and how it differs from passing normal command-line options.

It will probably take some time to track down and fix this one, so @michaelkuty, a temporary workaround might be to go ahead and enable global httpbasic authentication. Please let us know if you find a better workaround in the meantime.

**Comment by ankostis** [comment] 2016-03-23 16:19
Is it possible to launch it with the `verbosity` flag to 3?
That way we can see the actual arguments passed into pypiserver in the log-trace.

**Comment by luismsgomes** [comment] 2016-06-30 00:47
I think I fixed the propagation problem.  Please checkout my pull request #156.

**Comment by mplanchard** [comment] 2016-07-14 02:07
Agreed that this should be fixed with #156. @michaelkuty, can you verify using @luismsgomes's branch?

**Comment by redbaron4** [comment] 2017-09-19 12:04
Any update on this? I have just run into this issue. I can confirm that some of the options like `redirect_to_fallback = False` work but `password_file` and `authenticate` do not.

Apparently the fix has landed in the code but a new version has not been released. Is it in the pipeline?

My PyPIServer is supposed to work on a sub-path /pypi so I am using a PasteDeploy#prefix filter. Is there a way to do so using stock pypiserver?

**Comment by mplanchard** [comment] 2017-09-19 13:58
@redbaron4 could you check out the current master and verify that it works as expected? We believe that #156 fixed the issue, but have yet to receive verification from anyone who was affected by it. Also, @michaelkuty, could you verify that this issue does not occur with the current master branch?

**Comment by redbaron4** [comment] 2017-09-20 04:49
@mplanchard Well the server where I have hosted this does not have internet access but I did copy the entire `__init__.py` file from that PR to overwrite the existing 1.2.0's `__init__.py` file (I know bad practice but the fastest way to verify for me) and the PR worked correctly for the `password_file` and `redirect_to_fallback`. However, `authenticate` settings were not parsed and had no effect.

**Comment by mplanchard** [comment] 2017-11-30 02:08
@redbaron4 I believe #196 resolves the issue you pointed out with string parsing.

**Closed** 2017-12-03 22:22 UTC
Labels: type.Bug

**Comment by redbaron4** [comment] 2017-12-04 05:33
Thanks @mplanchard 

I tried the new v1.2.1 and it fixed the issue.
